In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pickle
from tensorflow.keras.models import load_model

In [17]:
# load trained model, scaller pickel and onehot encoded
model = load_model('model.h5')

with open('encoder.pkl', 'rb') as f:
    encoder = pickle.load(f)
with open('X_scaler.pkl', 'rb') as f:
    X_scaler = pickle.load(f)
with open('y_scaler.pkl', 'rb') as f:
    y_scaler = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [18]:
# Example input data
input_data = {
    'CreditScore': 119,
    'Geography': 'France',
    'Gender': 'Female',
    'Age': 42,
    'Tenure': 2,
    'Balance': 0,
    'NumOfProducts': 0,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'Exited': 1
}

In [19]:
geo_enc=encoder.transform([[input_data['Geography']]])
geo_enc_df=pd.DataFrame(geo_enc, columns=encoder.get_feature_names_out(['Geography']))
geo_enc_df

c:\Users\ankit\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [20]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,119,France,Female,42,2,0,0,1,1,1

In [21]:
# Drop original Geography column
input_df = input_df.drop('Geography', axis=1)

# Add encoded columns
input_df = pd.concat([input_df, geo_enc_df], axis=1)

input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,119,Female,42,2,0,0,1,1,1,1.0,0.0,0.0

In [22]:
if input_df['Gender'].iloc[0] == 'Male':
    input_df['Gender'] = 1                      
else:
    input_df['Gender'] = 0

In [23]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,119,0,42,2,0,0,1,1,1,1.0,0.0,0.0

In [12]:
# scaling the input data
input_df=X_scaler.transform(input_df)

In [14]:
pred=model.predict(input_df)
pred=y_scaler.inverse_transform(pred)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

array([[100916.3]], dtype=float32)