In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Churn_Modelling.csv')

In [4]:
df.drop(columns=['RowNumber', 'CustomerId','Surname'], inplace=True)

In [5]:
import pickle

In [6]:
df.Gender=df['Gender'].map({'Female':0,'Male':1})

In [7]:
from sklearn.preprocessing import OneHotEncoder
import pickle

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

encoded = encoder.fit_transform(df[['Geography']])

with open('encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

In [9]:
df = pd.get_dummies(df, columns=['Geography'], dtype=int)

In [10]:
with open("feature_columns.pkl", "wb") as file:
    pickle.dump(df.columns.tolist(), file)

In [11]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1,0,0

In [12]:
X = df.drop('EstimatedSalary', axis=1)
y = df['EstimatedSalary']

In [55]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,1,1,0,0
3,699,0,39,1,0.00,2,0,0,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,0,1,0,0

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)

In [16]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler()

X_train = X_scaler.fit_transform(X_train)
X_test = X_scaler.transform(X_test)

In [17]:
from sklearn.preprocessing import StandardScaler

y_scaler = StandardScaler()

y_train = y_scaler.fit_transform(y_train.values.reshape(-1,1))
y_test = y_scaler.transform(y_test.values.reshape(-1,1))

In [18]:
with open("X_scaler.pkl", "wb") as file:
    pickle.dump(X_scaler, file)
with open("y_scaler.pkl", "wb") as file:
    pickle.dump(y_scaler, file)

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [23]:
## build ann model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #hl1
    Dense(32, activation='relu'),#hl2
    Dense(16, activation='relu'),#hl3
    Dense(8, activation='relu'),#hl4
    Dense(4, activation='relu'),#hl5
    Dense(1)#output layer
])

In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,617 (14.13 KB)

 Trainable params: 3,617 (14.13 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)

In [44]:
model.compile(optimizer=opt, loss='mean_squared_error', metrics=['root_mean_squared_error'])

In [45]:
## set up tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [46]:
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [47]:
# setup early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=100, restore_best_weights=True)
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [48]:
# train the model
history =model.fit(
    X_train,
    y_train,validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorflow_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.9957 - root_mean_squared_error: 0.9978 - val_loss: 1.0040 - val_root_mean_squared_error: 1.0020
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9944 - root_mean_squared_error: 0.9972 - val_loss: 1.0056 - val_root_mean_squared_error: 1.0028
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.9930 - root_mean_squared_error: 0.9965 - val_loss: 1.0051 - val_root_mean_squared_error: 1.0025
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9920 - root_mean_squared_error: 0.9960 - val_loss: 1.0086 - val_root_mean_squared_error: 1.0043
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9902 - root_mean_squared_error: 0.9951 - val_loss: 1.0079 - val_root_mean_squared_error: 1.0039
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9891 - root_mean_squared_error: 0.9945 - val_loss: 1.0112 - val_root_mean_squared_error: 1.0056
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9878 - root_mean_squared_error: 0.9939 - val_loss: 1.0104 - val_root_mean_squared_error: 1.0052
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9858 - root_mean_squared_error: 0.9929 - val_loss: 1.0181 - val_root_mean_squared_error: 1.0090
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9836 - root_mean_squared_error: 0.9918 - val_loss: 1.0211 - val_root_mean_squared_error: 1.0105
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9832 - root_mean_squared_error: 0.9916 - val_loss: 1.0177 - val_root_mean_squared_error: 1.0088
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9797 - root_mean_squared_error: 0.9898 - val_loss: 1.0230 - val_root_mean_squared_error: 1.0114
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9794 - root_mean_squared_error: 0.9896 - val_loss: 1.0268 - val_root_mean_squared_error: 1.0133
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9735 - root_mean_squared_error: 0.9867 - val_loss: 1.0276 - val_root_mean_squared_error: 1.0137
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9745 - root_mean_squared_error: 0.9872 - val_loss: 1.0298 - val_root_mean_squared_error: 1.0148
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9715 - root_mean_squared_error: 0.9856 - val_loss: 1.0341 - val_root_mean_squared_error: 1.0169
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9703 - root_mean_squared_error: 0.9850 - val_loss: 1.0392 - val_root_mean_squared_error: 1.0194
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9644 - root_mean_squared_error: 0.9821 - val_loss: 1.0392 - val_root_mean_squared_error: 1.0194
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9612 - root_mean_squared_error: 0.9804 - val_loss: 1.0540 - val_root_mean_squared_error: 1.0266
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9538 - root_mean_squared_error: 0.9766 - val_loss: 1.0586 - val_root_mean_squared_error: 1.0289
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9535 - root_mean_squared_error: 0.9765 - val_loss: 1.0634 - val_root_mean_squared_error: 1.0312
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9512 - root_mean_squared_error: 0.9753 - val_loss: 1.0544 - val_root_mean_squared_error: 1.0269
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9455 - root_mean_squared_error: 0.9724 - val_loss: 1.0645 - val_root_mean_squared_error: 1.0317
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9430 - root_mean_squared_error: 0.9711 - val_loss: 1.0615 - val_root_mean_squared_error: 1.0303
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9360 - root_mean_squared_error: 0.9675 - val_loss: 1.0773 - val_root_mean_squared_error: 1.0379
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9317 - root_mean_squared_error: 0.9652 - val_loss: 1.0990 - val_root_mean_squared_error: 1.0483
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9287 - root_mean_squared_error: 0.9637 - val_loss: 1.0789 - val_root_mean_squared_error: 1.0387
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9209 - root_mean_squared_error: 0.9596 - val_loss: 1.0894 - val_root_mean_squared_error: 1.0437
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9205 - root_mean_squared_error: 0.9594 - val_loss: 1.1145 - val_root_mean_squared_error: 1.0557
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9077 - root_mean_squared_error: 0.9528 - val_loss: 1.1178 - val_root_mean_squared_error: 1.0573
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9102 - root_mean_squared_error: 0.9540 - val_loss: 1.0968 - val_root_mean_squared_error: 1.0473
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9034 - root_mean_squared_error: 0.9505 - val_loss: 1.1102 - val_root_mean_squared_error: 1.0537
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8976 - root_mean_squared_error: 0.9474 - val_loss: 1.1216 - val_root_mean_squared_error: 1.0591
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8882 - root_mean_squared_error: 0.9424 - val_loss: 1.1243 - val_root_mean_squared_error: 1.0603
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8865 - root_mean_squared_error: 0.9416 - val_loss: 1.1578 - val_root_mean_squared_error: 1.0760
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8841 - root_mean_squared_error: 0.9403 - val_loss: 1.1318 - val_root_mean_squared_error: 1.0638
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8787 - root_mean_squared_error: 0.9374 - val_loss: 1.1602 - val_root_mean_squared_error: 1.0771
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8751 - root_mean_squared_error: 0.9355 - val_loss: 1.1524 - val_root_mean_squared_error: 1.0735
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8658 - root_mean_squared_error: 0.9305 - val_loss: 1.1624 - val_root_mean_squared_error: 1.0781
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8649 - root_mean_squared_error: 0.9300 - val_loss: 1.1729 - val_root_mean_squared_error: 1.0830
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8598 - root_mean_squared_error: 0.9272 - val_loss: 1.1548 - val_root_mean_squared_error: 1.0746
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8523 - root_mean_squared_error: 0.9232 - val_loss: 1.1701 - val_root_mean_squared_error: 1.0817
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8504 - root_mean_squared_error: 0.9222 - val_loss: 1.1675 - val_root_mean_squared_error: 1.0805
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8451 - root_mean_squared_error: 0.9193 - val_loss: 1.1880 - val_root_mean_squared_error: 1.0899
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8398 - root_mean_squared_error: 0.9164 - val_loss: 1.1841 - val_root_mean_squared_error: 1.0882
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8418 - root_mean_squared_error: 0.9175 - val_loss: 1.1661 - val_root_mean_squared_error: 1.0799
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8318 - root_mean_squared_error: 0.9120 - val_loss: 1.2018 - val_root_mean_squared_error: 1.0963
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8257 - root_mean_squared_error: 0.9087 - val_loss: 1.1987 - val_root_mean_squared_error: 1.0949
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8215 - root_mean_squared_error: 0.9063 - val_loss: 1.1977 - val_root_mean_squared_error: 1.0944
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8176 - root_mean_squared_error: 0.9042 - val_loss: 1.2442 - val_root_mean_squared_error: 1.1154
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8134 - root_mean_squared_error: 0.9019 - val_loss: 1.2307 - val_root_mean_squared_error: 1.1094
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8140 - root_mean_squared_error: 0.9022 - val_loss: 1.2151 - val_root_mean_squared_error: 1.1023
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8023 - root_mean_squared_error: 0.8957 - val_loss: 1.2421 - val_root_mean_squared_error: 1.1145
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8091 - root_mean_squared_error: 0.8995 - val_loss: 1.2330 - val_root_mean_squared_error: 1.1104
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8034 - root_mean_squared_error: 0.8963 - val_loss: 1.2348 - val_root_mean_squared_error: 1.1112
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7997 - root_mean_squared_error: 0.8942 - val_loss: 1.2489 - val_root_mean_squared_error: 1.1176
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7986 - root_mean_squared_error: 0.8937 - val_loss: 1.2448 - val_root_mean_squared_error: 1.1157
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7916 - root_mean_squared_error: 0.8897 - val_loss: 1.2734 - val_root_mean_squared_error: 1.1285
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7922 - root_mean_squared_error: 0.8901 - val_loss: 1.2541 - val_root_mean_squared_error: 1.1198
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7879 - root_mean_squared_error: 0.8876 - val_loss: 1.2594 - val_root_mean_squared_error: 1.1222
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7813 - root_mean_squared_error: 0.8839 - val_loss: 1.2317 - val_root_mean_squared_error: 1.1098
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7748 - root_mean_squared_error: 0.8802 - val_loss: 1.2699 - val_root_mean_squared_error: 1.1269
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7817 - root_mean_squared_error: 0.8841 - val_loss: 1.3057 - val_root_mean_squared_error: 1.1427
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7791 - root_mean_squared_error: 0.8827 - val_loss: 1.2632 - val_root_mean_squared_error: 1.1239
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7705 - root_mean_squared_error: 0.8778 - val_loss: 1.2656 - val_root_mean_squared_error: 1.1250
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7715 - root_mean_squared_error: 0.8783 - val_loss: 1.2794 - val_root_mean_squared_error: 1.1311
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7626 - root_mean_squared_error: 0.8733 - val_loss: 1.3010 - val_root_mean_squared_error: 1.1406
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7628 - root_mean_squared_error: 0.8734 - val_loss: 1.2939 - val_root_mean_squared_error: 1.1375
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7564 - root_mean_squared_error: 0.8697 - val_loss: 1.2847 - val_root_mean_squared_error: 1.1335
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7586 - root_mean_squared_error: 0.8710 - val_loss: 1.2476 - val_root_mean_squared_error: 1.1169
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7599 - root_mean_squared_error: 0.8717 - val_loss: 1.2907 - val_root_mean_squared_error: 1.1361
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7567 - root_mean_squared_error: 0.8699 - val_loss: 1.3203 - val_root_mean_squared_error: 1.1490
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7543 - root_mean_squared_error: 0.8685 - val_loss: 1.3079 - val_root_mean_squared_error: 1.1436
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7490 - root_mean_squared_error: 0.8655 - val_loss: 1.3170 - val_root_mean_squared_error: 1.1476
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7455 - root_mean_squared_error: 0.8634 - val_loss: 1.2833 - val_root_mean_squared_error: 1.1328
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7443 - root_mean_squared_error: 0.8627 - val_loss: 1.2895 - val_root_mean_squared_error: 1.1356
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7391 - root_mean_squared_error: 0.8597 - val_loss: 1.3157 - val_root_mean_squared_error: 1.1470
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7363 - root_mean_squared_error: 0.8581 - val_loss: 1.2813 - val_root_mean_squared_error: 1.1320
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7377 - root_mean_squared_error: 0.8589 - val_loss: 1.3206 - val_root_mean_squared_error: 1.1492
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7348 - root_mean_squared_error: 0.8572 - val_loss: 1.3508 - val_root_mean_squared_error: 1.1622
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7325 - root_mean_squared_error: 0.8559 - val_loss: 1.3081 - val_root_mean_squared_error: 1.1437
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7273 - root_mean_squared_error: 0.8528 - val_loss: 1.2827 - val_root_mean_squared_error: 1.1326
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7271 - root_mean_squared_error: 0.8527 - val_loss: 1.3253 - val_root_mean_squared_error: 1.1512
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7283 - root_mean_squared_error: 0.8534 - val_loss: 1.3321 - val_root_mean_squared_error: 1.1542
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7253 - root_mean_squared_error: 0.8517 - val_loss: 1.3744 - val_root_mean_squared_error: 1.1723
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7244 - root_mean_squared_error: 0.8511 - val_loss: 1.3231 - val_root_mean_squared_error: 1.1503
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7169 - root_mean_squared_error: 0.8467 - val_loss: 1.3392 - val_root_mean_squared_error: 1.1573
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7160 - root_mean_squared_error: 0.8461 - val_loss: 1.3246 - val_root_mean_squared_error: 1.1509
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7134 - root_mean_squared_error: 0.8446 - val_loss: 1.3466 - val_root_mean_squared_error: 1.1604
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7156 - root_mean_squared_error: 0.8459 - val_loss: 1.3739 - val_root_mean_squared_error: 1.1721
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7132 - root_mean_squared_error: 0.8445 - val_loss: 1.3425 - val_root_mean_squared_error: 1.1587
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7140 - root_mean_squared_error: 0.8450 - val_loss: 1.3358 - val_root_mean_squared_error: 1.1558
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7095 - root_mean_squared_error: 0.8423 - val_loss: 1.3268 - val_root_mean_squared_error: 1.1519
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7054 - root_mean_squared_error: 0.8399 - val_loss: 1.3511 - val_root_mean_squared_error: 1.1624
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7075 - root_mean_squared_error: 0.8411 - val_loss: 1.3591 - val_root_mean_squared_error: 1.1658
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7031 - root_mean_squared_error: 0.8385 - val_loss: 1.3591 - val_root_mean_squared_error: 1.1658
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7041 - root_mean_squared_error: 0.8391 - val_loss: 1.3461 - val_root_mean_squared_error: 1.1602
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6994 - root_mean_squared_error: 0.8363 - val_loss: 1.3090 - val_root_mean_squared_error: 1.1441
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7016 - root_mean_squared_error: 0.8376 - val_loss: 1.3763 - val_root_mean_squared_error: 1.1731
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6996 - root_mean_squared_error: 0.8364 - val_loss: 1.3478 - val_root_mean_squared_error: 1.1610
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6956 - root_mean_squared_error: 0.8340 - val_loss: 1.3677 - val_root_mean_squared_error: 1.1695

In [51]:
df['EstimatedSalary'].describe()

count     10000.000000
mean     100090.239881
std       57510.492818
min          11.580000
25%       51002.110000
50%      100193.915000
75%      149388.247500
max      199992.480000
Name: EstimatedSalary, dtype: float64

In [52]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [54]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1,0,0